services:
  db:
    image: postgres:15.3
    environment:
      POSTGRES_DB: liquor_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 15432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
  localstack:
    image: localstack/localstack:2.1.0
    environment:
      SERVICES: s3
      DEFAULT_REGION: ap-northeast-1
      S3_PORT: 4572
    ports:
      - 14572:4572
