spring.profiles.active: test

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    jdbc-url: jdbc:mysql://localhost:13406/liquor-notes-test?rewriteBatchedStatements=true
    username: mysql
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
aws:
  s3:
    endpoint: http://localhost:14572
    region: ap-northeast-1
    bucket: liquor-notes
